### ISSUE TITLE
Buttons to move arrow left/right

### ISSUE THREAD

**Issue by billyjoker** [robinst/frozen-bubble-android#1]
Hi, i'd like to add two buttons in order to move the arrow left-right with a fixed speed, Where should i implement this function?

Congratulations for your work, it is awesome!!!

**Comment by robinst** [comment]
Hey. It's not my work, this is just an outdated mirror of the Subversion repository. Please create an issue here instead and contribute there: https://code.google.com/p/frozenbubbleandroid/issues/list
